---
title: "Class2-R_Markdown"
author: "Varshini Selvadurai"
date: "`r Sys.Date()`"
output: pdf_document
---

## Install Libraries
```{r echo = FALSE}
library(httr) #webapi
library(jsonlite) #makes it json data
library(ggplot2) #plotting
library(dplyr)
library(purrr)
library(knitr)
# get the API key from here -> https://docs.airnowapi.org/account/request/
# set the API_KEY env variable from the command line so that we dont have
# store it in the code
API_KEY <- Sys.getenv("API_KEY")

dates = c("2018-07-09","2018-07-10","2018-07-11","2018-07-12","2018-07-13","2018-07-14","2018-07-15")
get_data <- function(date){
  airnow_api_host <- "http://www.airnowapi.org"
  url <- paste0(airnow_api_host, "/aq/forecast/zipCode/?format=application/json&zipCode=20871&date=",date,"&distance=25&API_KEY=", API_KEY)
  resp   <- GET(url)
  print(status_code(resp))
  resp_df   <- fromJSON(content(resp, "text"))
  #View(head(resp_df, n = 2))
  return (head(resp_df, n = 2))
}
x = map(dates,get_data)
total <- x[1][[1]]
total$Category <-NULL
for (i in seq(2:7)){
  x[i][[1]]$Category <- NULL
  total <- rbind(total, x[i][[1]])
}
```


## Data for 1 week

```{r echo = FALSE}
kable(total)
```

## AQI by Date

You can also embed plots, for example:

```{r echo=FALSE}
total %>%
  ggplot(aes(x = as.Date(DateForecast), y = AQI)) +
  geom_line(aes(col=ParameterName), size = 2) +
  geom_point() +
  theme_minimal()
```

